"""Streamlit Auto Repair Orders app — Google Sheets backend.

Quick setup (Service Account)
-----------------------------
1) In Google Cloud Console:
   - Create/select a project
   - Enable **Google Sheets API**
   - Create a **Service Account** and download the JSON key file

2) Share your target Google Sheet with the service account email
   (it looks like: something@project-id.iam.gserviceaccount.com)

3) Set these environment variables when running Streamlit:

   - GOOGLE_SHEETS_SPREADSHEET_ID : the spreadsheet id (from the URL)
   - GOOGLE_SHEETS_WORKSHEET_NAME : optional, default "Orders"
   - GOOGLE_SERVICE_ACCOUNT_JSON  : path to the downloaded key file
   - GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT : optional full JSON content for hosted deploys

Example:
  export GOOGLE_SHEETS_SPREADSHEET_ID='1AbC...'
  export GOOGLE_SHEETS_WORKSHEET_NAME='Orders'
  export GOOGLE_SERVICE_ACCOUNT_JSON='/path/to/service_account.json'
  streamlit run app_gsheets.py

Notes
-----
- This app requires Google Sheets to be configured. No local storage fallback.
- This app writes the *entire* table back to the sheet when you click Save.
  That keeps things simple and reliable.
- "Total Price" and "Profit" columns are excluded from writes (auto-generated by formulas).
- If multiple people will edit concurrently, consider switching to an
  append/update-by-Order-ID strategy.
"""

import os
import re
import time
import json
import html
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

import pandas as pd
import streamlit as st
import altair as alt

# Google Sheets API (google-api-python-client)
try:
    from google.oauth2.service_account import Credentials
    import google_auth_httplib2
    import httplib2
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
except Exception:  # pragma: no cover
    Credentials = None
    google_auth_httplib2 = None
    httplib2 = None
    build = None
    HttpError = None


APP_DIR = Path(__file__).parent
DATA_DIR = APP_DIR / "data"
EXPORT_DIR = DATA_DIR / "exports"

COLUMNS = [
    "Order Status",
    "Order ID",
    "Date",
    "Time",
    "Address",
    "Customer",
    "Vehicle (Year Make Model)",
    "Plate",
    "VIN",
    "Mileage",
    "Job / Notes",
    "Labor",
    "Part Name",
    "Part Status",
    "Part Notes",
    "Part Cost",
    "Part Price",
    "Total Price",
    "Profit",
    "Paid?",
    "Last Updated",
    "Internal Notes",
]

ORDER_STATUS_OPTIONS = ["New", "In Progress", "Completed", "Canceled", "Warranty Follow-up"]
PART_STATUS_OPTIONS = ["Ordered", "Arrived", "Installed", "Returned", "Backorder", "Canceled"]
PAID_OPTIONS = ["Yes", "No"]

REAL_ORDER_COLUMNS = [
    "Order Status",
    "Date",
    "Time",
    "Address",
    "Customer",
    "Vehicle (Year Make Model)",
    "Plate",
    "VIN",
    "Mileage",
    "Job / Notes",
    "Labor",
    "Part Name",
    "Part Status",
    "Part Notes",
    "Part Cost",
    "Part Price",
]

ORDER_SUMMARY_COLUMNS = [
    "Order Status",
    "Date",
    "Time",
    "Customer",
    "Vehicle (Year Make Model)",
    "Job / Notes",
    "Total Price",
    "Profit",
    "Paid?",
]


def ensure_dirs() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def clean_price_value(value):
    """Clean price values: strip $ and commas, convert (123.45) to -123.45, handle None/N/A."""
    if pd.isna(value) or value == "" or value is None:
        return None
    
    # Convert to string for processing
    val_str = str(value).strip()
    
    # Treat "None", "N/A", "n/a", "NA", "na" as empty
    if val_str.upper() in ["NONE", "N/A", "NA", ""]:
        return None
    
    # Remove $ and commas
    val_str = val_str.replace("$", "").replace(",", "").strip()
    
    # Handle accounting format: (123.45) means negative
    if val_str.startswith("(") and val_str.endswith(")"):
        val_str = "-" + val_str[1:-1]
    
    # Try to convert to float
    try:
        result = float(val_str)
        return result
    except (ValueError, TypeError):
        return None


def normalize_df(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure all required columns exist, order columns, and coerce numeric fields."""
    if df is None or df.empty:
        df = pd.DataFrame(columns=COLUMNS)
    else:
        df = df.copy()
        df.columns = [str(c).strip().lstrip("\ufeff") for c in df.columns]
        df = df.loc[:, [c != "" and c.lower() != "nan" for c in df.columns]]
        df = df.loc[:, ~df.columns.duplicated()].copy()

    for c in COLUMNS:
        if c not in df.columns:
            df[c] = ""

    df = df[COLUMNS].copy()

    # Clean and convert price columns
    for col in ["Labor", "Part Cost", "Part Price", "Total Price", "Profit"]:
        if col in df.columns:
            df[col] = df[col].apply(clean_price_value)
    
    # Handle Mileage separately (no $ or accounting format)
    if "Mileage" in df.columns:
        df["Mileage"] = df["Mileage"].apply(
            lambda x: None if (pd.isna(x) or str(x).strip().upper() in ["NONE", "N/A", "NA", ""]) 
            else pd.to_numeric(x, errors="coerce")
        )

    # Round price columns to 2 decimal places
    for price_col in ["Labor", "Part Cost", "Part Price", "Total Price", "Profit"]:
        if price_col in df.columns:
            df[price_col] = df[price_col].round(2)
    
    return df


def real_order_mask(df: pd.DataFrame) -> pd.Series:
    """Return rows that contain actual order details, not blank sheet/formula rows."""
    if df is None or df.empty:
        return pd.Series(dtype=bool)

    cols = [c for c in REAL_ORDER_COLUMNS if c in df.columns]
    if not cols:
        return pd.Series(False, index=df.index)

    meaningful = pd.Series(False, index=df.index)
    for col in cols:
        series = df[col]
        if col in ["Labor", "Part Cost", "Part Price", "Mileage"]:
            meaningful = meaningful | pd.to_numeric(series, errors="coerce").notna()
        else:
            meaningful = meaningful | series.fillna("").astype(str).str.strip().ne("")
    return meaningful


def real_orders_df(df: pd.DataFrame) -> pd.DataFrame:
    """Drop blank rows that only exist because formulas remain in Google Sheets."""
    if df is None or df.empty:
        return normalize_df(pd.DataFrame(columns=COLUMNS))
    return df.loc[real_order_mask(df)].copy()


def parse_order_date(date_value):
    if pd.isna(date_value) or str(date_value).strip() == "":
        return pd.NaT

    date_str = str(date_value).strip()
    for fmt in ["%Y-%m-%d", "%m/%d/%Y", "%m.%d.%Y", "%Y/%m/%d", "%m-%d-%Y"]:
        parsed = pd.to_datetime(date_str, format=fmt, errors="coerce")
        if pd.notna(parsed):
            return parsed
    return pd.to_datetime(date_str, errors="coerce")


def service_category(job_notes: str, part_name: str) -> str:
    text = f"{job_notes or ''} {part_name or ''}".lower()
    if any(word in text for word in ["brake", "pad", "rotor"]):
        return "Brakes"
    if any(word in text for word in ["spark", "ignition", "coil"]):
        return "Ignition"
    if any(word in text for word in ["check engine", "engine light", "diagnostic"]):
        return "Diagnostic"
    if any(word in text for word in ["wiper", "blade"]):
        return "Wipers"
    if any(word in text for word in ["seal", "rubber", "window"]):
        return "Seal / Trim"
    if str(job_notes or "").strip() or str(part_name or "").strip():
        return "Other"
    return "Uncategorized"


def dashboard_df(df: pd.DataFrame) -> pd.DataFrame:
    dfx = real_orders_df(df).copy()
    for col in ["Labor", "Part Cost", "Part Price", "Total Price", "Profit"]:
        dfx[col] = pd.to_numeric(dfx[col], errors="coerce").fillna(0)

    dfx["Date Parsed"] = pd.to_datetime(dfx["Date"].apply(parse_order_date), errors="coerce")
    dfx["Month"] = dfx["Date Parsed"].dt.to_period("M").dt.to_timestamp()
    dfx["Week"] = dfx["Date Parsed"].dt.to_period("W").dt.start_time
    dfx["Gross Margin %"] = dfx.apply(
        lambda row: (row["Profit"] / row["Total Price"] * 100) if row["Total Price"] else 0,
        axis=1,
    )
    dfx["Service Category"] = dfx.apply(
        lambda row: service_category(row.get("Job / Notes", ""), row.get("Part Name", "")),
        axis=1,
    )
    dfx["Paid Status"] = dfx["Paid?"].fillna("").astype(str).str.strip().replace("", "Unknown")
    dfx["Customer Display"] = dfx["Customer"].fillna("").astype(str).str.strip().replace("", "Missing customer")
    return dfx


def money(value) -> str:
    if pd.isna(value) or value == "":
        return "$0.00"
    return f"${float(value or 0):,.2f}"


def payment_income_summary(dfx: pd.DataFrame) -> dict[str, dict[str, float]]:
    summary = {
        "Cash": {"orders": 0, "total": 0.0},
        "Zelle": {"orders": 0, "total": 0.0},
    }
    if dfx is None or dfx.empty or "Paid Status" not in dfx.columns:
        return summary

    for payment_type in summary:
        payment_rows = dfx[dfx["Paid Status"].str.lower().eq(payment_type.lower())]
        summary[payment_type]["orders"] = int(len(payment_rows))
        summary[payment_type]["total"] = float(payment_rows["Total Price"].sum())
    return summary


def render_payment_income_card(label: str, orders: int, total: float) -> None:
    st.markdown(
        (
            f'<div class="tw-payment-card">'
            f'<div class="tw-payment-title">{html.escape(label)}</div>'
            f'<div class="tw-payment-amount">{money(total)}</div>'
            f'<div class="tw-payment-foot">{orders} orders</div>'
            f'</div>'
        ),
        unsafe_allow_html=True,
    )


def quick_stat_windows(dfx: pd.DataFrame):
    today = pd.Timestamp(datetime.now().date())
    week_start = today - pd.Timedelta(days=today.weekday())
    biweekly_start = week_start - pd.Timedelta(days=7)
    month_start = today.replace(day=1)
    week_end = week_start + pd.Timedelta(days=6)
    biweekly_end = biweekly_start + pd.Timedelta(days=13)
    month_end = month_start + pd.offsets.MonthEnd(0)
    previous_week_start = week_start - pd.Timedelta(days=7)
    previous_biweekly_start = biweekly_start - pd.Timedelta(days=14)
    previous_month_start = (month_start - pd.offsets.MonthBegin(1)).normalize()

    dated = dfx[dfx["Date Parsed"].notna()].copy()
    dated = dated[dated["Date Parsed"].dt.normalize() <= today]
    date_values = dated["Date Parsed"].dt.normalize()

    return [
        (
            "This Week",
            f"Since {week_start:%b %d}",
            dated[date_values >= week_start],
            dated[(date_values >= previous_week_start) & (date_values < week_start)],
            "last full week",
            week_end,
        ),
        (
            "Biweekly",
            f"Since {biweekly_start:%b %d}",
            dated[date_values >= biweekly_start],
            dated[(date_values >= previous_biweekly_start) & (date_values < biweekly_start)],
            "previous full biweek",
            biweekly_end,
        ),
        (
            "Month-to-Date",
            f"Since {month_start:%b %d}",
            dated[date_values >= month_start],
            dated[(date_values >= previous_month_start) & (date_values < month_start)],
            "last full month",
            month_end,
        ),
        ("Overall", "All real orders", dfx, None, "", None),
    ]


def days_left_label(end_date: Optional[pd.Timestamp]) -> str:
    if end_date is None:
        return ""

    today = pd.Timestamp(datetime.now().date())
    days_left = max(int((end_date.normalize() - today).days), 0)
    day_word = "day" if days_left == 1 else "days"
    return f"{days_left} {day_word} left · ends {end_date:%b %d}"


def pct_of_previous(current_value, previous_value) -> str:
    current_value = float(current_value or 0)
    previous_value = float(previous_value or 0)
    if previous_value == 0:
        return "N/A" if current_value else "0%"
    return f"{current_value / previous_value * 100:.0f}%"


def comparison_bar_html(label: str, current_value, previous_value, value_text: str) -> str:
    current_value = float(current_value or 0)
    previous_value = float(previous_value or 0)
    if previous_value == 0:
        percent_text = "N/A" if current_value else "0%"
        bar_width = 0
    else:
        percent = current_value / previous_value * 100
        percent_text = f"{percent:.0f}%"
        bar_width = max(0, min(percent, 100))

    return (
        f'<div class="tw-stat-compare">'
        f'<div class="tw-stat-compare-top">'
        f'<span>{html.escape(label)}</span>'
        f'<strong>{html.escape(value_text)}</strong>'
        f'</div>'
        f'<div class="tw-stat-bar-row">'
        f'<div class="tw-stat-bar" aria-label="{html.escape(label)} {html.escape(percent_text)}">'
        f'<div class="tw-stat-bar-fill" style="width: {bar_width:.0f}%;"></div>'
        f'</div>'
        f'<span class="tw-stat-bar-pct">{html.escape(percent_text)}</span>'
        f'</div>'
        f'</div>'
    )


def render_quick_stat_card(
    title: str,
    subtitle: str,
    window_df: pd.DataFrame,
    previous_df: Optional[pd.DataFrame] = None,
    previous_label: str = "",
    end_date: Optional[pd.Timestamp] = None,
) -> None:
    revenue = window_df["Total Price"].sum()
    profit = window_df["Profit"].sum()
    part_cost = window_df["Part Cost"].sum()
    previous_orders = 0 if previous_df is None else len(previous_df)
    previous_revenue = 0 if previous_df is None else previous_df["Total Price"].sum()
    previous_profit = 0 if previous_df is None else previous_df["Profit"].sum()
    comparison_html = ""
    if previous_df is not None:
        comparison_html = (
            f'<div class="tw-stat-compare-label">Previous: {html.escape(previous_label)}</div>'
            f'{comparison_bar_html("Orders", len(window_df), previous_orders, str(previous_orders))}'
            f'{comparison_bar_html("Revenue", revenue, previous_revenue, money(previous_revenue))}'
            f'{comparison_bar_html("Profit", profit, previous_profit, money(previous_profit))}'
        )
    days_left_html = ""
    days_left = days_left_label(end_date)
    if days_left:
        days_left_html = f'<div class="tw-stat-days-left">{html.escape(days_left)}</div>'

    st.markdown(
        (
            f'<div class="tw-stat-card">'
            f'<div class="tw-stat-title">{html.escape(title)}</div>'
            f'<div class="tw-stat-subtitle">{html.escape(subtitle)}</div>'
            f'{days_left_html}'
            f'<div class="tw-stat-primary">{int(len(window_df))}</div>'
            f'<div class="tw-stat-label">Orders</div>'
            f'<div class="tw-stat-row"><span>Revenue</span><strong>{money(revenue)}</strong></div>'
            f'<div class="tw-stat-row"><span>Profit</span><strong>{money(profit)}</strong></div>'
            f'<div class="tw-stat-foot">Parts cost {money(part_cost)}</div>'
            f'{comparison_html}'
            f'</div>'
        ),
        unsafe_allow_html=True,
    )


def order_overview_df(df: pd.DataFrame, days: int = 30) -> pd.DataFrame:
    dfx = df.copy()
    parsed_dates = pd.to_datetime(dfx["Date"].apply(parse_order_date), errors="coerce")
    today = pd.Timestamp(datetime.now().date())
    start_date = today - pd.Timedelta(days=days - 1)
    normalized_dates = parsed_dates.dt.normalize()
    recent_mask = parsed_dates.notna() & (normalized_dates >= start_date) & (normalized_dates <= today)
    future_mask = parsed_dates.notna() & (normalized_dates > today)
    active_status = dfx["Order Status"].fillna("").astype(str).str.strip().isin(
        ["New", "In Progress", "Warranty Follow-up"]
    )
    mask = recent_mask | future_mask | active_status
    dfx = dfx.loc[mask].copy()
    dfx["_Date Parsed"] = parsed_dates.loc[dfx.index]
    dfx["_Has Valid Date"] = dfx["_Date Parsed"].notna()
    dfx["_Date Distance"] = (dfx["_Date Parsed"].dt.normalize() - today).abs()
    dfx = dfx.sort_values(
        ["_Has Valid Date", "_Date Distance", "_Date Parsed", "Time"],
        ascending=[False, True, True, True],
        na_position="last",
    )
    return dfx.drop(columns=["_Date Parsed", "_Has Valid Date", "_Date Distance"])


def table_height(row_count: int) -> int:
    return max(180, 38 + (row_count + 1) * 35)


def style_order_table(data: pd.DataFrame):
    def cell_styles(row):
        styles = []
        status = str(row.get("Order Status", "") or "").strip()
        paid = str(row.get("Paid?", "") or "").strip().lower()

        for col in row.index:
            style = ""
            if col == "Order Status":
                if status == "New":
                    style = "font-weight: 650;"
                elif status == "In Progress":
                    style = "font-weight: 650;"
                elif status == "Completed":
                    style = "font-weight: 650;"
                elif status == "Canceled":
                    style = "font-weight: 650; opacity: 0.72;"
                elif status == "Warranty Follow-up":
                    style = "font-weight: 650;"
            elif col == "Paid?":
                if paid == "yes":
                    style = "font-weight: 650;"
                elif paid == "no":
                    style = "font-weight: 650;"
            styles.append(style)
        return styles

    return data.style.apply(cell_styles, axis=1).format(
        {
            "Labor": money,
            "Part Cost": money,
            "Part Price": money,
            "Total Price": money,
            "Profit": money,
        },
        na_rep="",
    )


# -----------------------------
# Google Sheets backend
# -----------------------------
def _streamlit_secret(name: str, default=None):
    try:
        return st.secrets.get(name, default)
    except Exception:
        return default


def _sheets_env() -> Tuple[Optional[str], str, Optional[str]]:
    spreadsheet_id = os.getenv("GOOGLE_SHEETS_SPREADSHEET_ID") or _streamlit_secret(
        "GOOGLE_SHEETS_SPREADSHEET_ID"
    )
    worksheet_name = os.getenv("GOOGLE_SHEETS_WORKSHEET_NAME") or _streamlit_secret(
        "GOOGLE_SHEETS_WORKSHEET_NAME",
        "Orders",
    )
    sa_json_path = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON") or _streamlit_secret(
        "GOOGLE_SERVICE_ACCOUNT_JSON"
    )
    return spreadsheet_id, worksheet_name, sa_json_path


def _service_account_json() -> Optional[str]:
    json_content = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT") or _streamlit_secret(
        "GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT"
    )
    if json_content:
        return str(json_content)

    service_account = _streamlit_secret("google_service_account")
    if service_account:
        return json.dumps(dict(service_account))

    return None


def gsheets_enabled() -> bool:
    spreadsheet_id, _, sa_json_path = _sheets_env()
    return bool(spreadsheet_id and (sa_json_path or _service_account_json()) and Credentials and build)


@st.cache_resource
def get_sheets_service(sa_json_path: Optional[str], sa_json: Optional[str]):
    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
    if sa_json:
        creds = Credentials.from_service_account_info(json.loads(sa_json), scopes=scopes)
    else:
        creds = Credentials.from_service_account_file(sa_json_path, scopes=scopes)

    if google_auth_httplib2 is not None and httplib2 is not None:
        authed_http = google_auth_httplib2.AuthorizedHttp(
            creds,
            http=httplib2.Http(timeout=12),
        )
        return build("sheets", "v4", http=authed_http, cache_discovery=False)

    return build("sheets", "v4", credentials=creds, cache_discovery=False)


def get_column_letter(n):
    result = ""
    while n > 0:
        n -= 1
        result = chr(65 + (n % 26)) + result
        n //= 26
    return result


def execute_sheets_request(request, action: str, attempts: int = 2):
    last_error = None
    for attempt in range(1, attempts + 1):
        try:
            return request.execute(num_retries=0)
        except Exception as e:
            last_error = e
            if HttpError is not None and isinstance(e, HttpError):
                status = getattr(e.resp, "status", None)
                if status is not None and 400 <= int(status) < 500:
                    raise
            if attempt == attempts:
                break
            time.sleep(min(2 ** (attempt - 1), 5))

    raise RuntimeError(
        f"Google Sheets {action} failed after {attempts} attempts. "
        "Please check your internet connection and try Reload from source. "
        f"Last error: {last_error}"
    )


def sheet_cell_value(row: pd.Series, col: str):
    numeric_cols = ["Labor", "Part Cost", "Part Price", "Mileage"]
    val = row.get(col, "")
    if col in numeric_cols:
        if pd.notna(val) and val != "" and str(val).strip().upper() not in ["NONE", "N/A", "NA"]:
            try:
                return float(val)
            except (ValueError, TypeError):
                return ""
        return ""

    if pd.notna(val) and val != "" and str(val).strip().upper() not in ["NONE", "N/A", "NA", "NAN"]:
        return str(val)
    return ""


def load_orders_gsheets() -> pd.DataFrame:
    spreadsheet_id, worksheet_name, sa_json_path = _sheets_env()
    service = get_sheets_service(sa_json_path, None if sa_json_path else _service_account_json())

    # Read full used range. We expect headers in row 1.
    rng = f"{worksheet_name}!A1:Z"  # plenty wide
    resp = execute_sheets_request(
        service.spreadsheets().values().get(spreadsheetId=spreadsheet_id, range=rng),
        "load",
    )
    values = resp.get("values", [])
    if not values:
        return normalize_df(pd.DataFrame(columns=COLUMNS))

    header = values[0]
    rows = values[1:] if len(values) > 1 else []
    df = pd.DataFrame(rows, columns=header)
    return normalize_df(df)


def save_orders_gsheets(df: pd.DataFrame) -> list[str]:
    spreadsheet_id, worksheet_name, sa_json_path = _sheets_env()
    service = get_sheets_service(sa_json_path, None if sa_json_path else _service_account_json())

    df = normalize_df(df.copy())
    df["Last Updated"] = now_str()

    # Columns to exclude from writing (these are auto-generated by formulas in Google Sheets)
    excluded_cols = ["Total Price", "Profit"]
    
    # Get columns to write (all columns except excluded ones)
    cols_to_write = [col for col in COLUMNS if col not in excluded_cols]
    
    # Convert to 2D list with proper types
    # Numeric columns should be numbers, not strings
    numeric_cols = ["Labor", "Part Cost", "Part Price", "Mileage"]
    
    # Build rows with proper data types (only writable columns)
    rows = []
    for _, row in df.iterrows():
        row_data = []
        for col in cols_to_write:
            if col in numeric_cols and col in df.columns:
                val = row[col]
                # Send as number if valid (including 0), otherwise empty string
                if pd.notna(val) and val != "" and str(val).strip().upper() not in ["NONE", "N/A", "NA"]:
                    try:
                        row_data.append(float(val))
                    except (ValueError, TypeError):
                        row_data.append("")
                else:
                    row_data.append("")
            else:
                val = row[col]
                # For text columns, convert to string, handle None/NaN
                if pd.notna(val) and val != "" and str(val).strip().upper() not in ["NONE", "N/A", "NA", "NAN"]:
                    row_data.append(str(val))
                else:
                    row_data.append("")
        rows.append(row_data)
    
    num_rows = len(rows) + 1  # +1 for header row
    
    # Build data for batch update - write column by column to skip protected ones
    # We need to map each column in cols_to_write to its actual position in COLUMNS
    batch_data = []
    
    for col_idx, col_name in enumerate(COLUMNS):
        if col_name in excluded_cols:
            continue
        
        # Get the index of this column in cols_to_write
        if col_name not in cols_to_write:
            continue
            
        write_idx = cols_to_write.index(col_name)
        col_letter = get_column_letter(col_idx + 1)
        
        # Extract this column's data from all rows. Do not rewrite row 1 headers:
        # many sheets protect the header row while allowing data rows to be edited.
        column_values = []
        for row in rows:
            column_values.append([row[write_idx]])
        
        range_name = f"{worksheet_name}!{col_letter}2:{col_letter}{num_rows}"
        batch_data.append({
            "range": range_name,
            "column": col_name,
            "values": column_values
        })
    
    # Use batchUpdate to write all columns at once
    body = {
        "valueInputOption": "USER_ENTERED",
        "data": [
            {"range": item["range"], "values": item["values"]}
            for item in batch_data
        ]
    }
    try:
        execute_sheets_request(
            service.spreadsheets().values().batchUpdate(
                spreadsheetId=spreadsheet_id,
                body=body
            ),
            "save",
        )
        return []
    except Exception:
        skipped_columns = []
        for item in batch_data:
            single_body = {
                "valueInputOption": "USER_ENTERED",
                "data": [{"range": item["range"], "values": item["values"]}],
            }
            try:
                execute_sheets_request(
                    service.spreadsheets().values().batchUpdate(
                        spreadsheetId=spreadsheet_id,
                        body=single_body
                    ),
                    f"save column {item['column']}",
                )
            except Exception:
                skipped_columns.append(item["column"])

        if len(skipped_columns) == len(batch_data):
            raise
        return skipped_columns


def next_order_row_gsheets(service, spreadsheet_id: str, worksheet_name: str) -> int:
    resp = execute_sheets_request(
        service.spreadsheets().values().get(
            spreadsheetId=spreadsheet_id,
            range=f"{worksheet_name}!A2:Q",
        ),
        "find next order row",
    )
    values = resp.get("values", [])
    last_used_offset = 0
    for idx, row_values in enumerate(values, start=1):
        if any(str(cell).strip() for cell in row_values):
            last_used_offset = idx
    return last_used_offset + 2


def append_order_gsheets(row: pd.Series) -> list[str]:
    spreadsheet_id, worksheet_name, sa_json_path = _sheets_env()
    service = get_sheets_service(sa_json_path, None if sa_json_path else _service_account_json())

    row = row.copy()
    row["Last Updated"] = now_str()

    row_number = next_order_row_gsheets(service, spreadsheet_id, worksheet_name)

    # Write only editable order-entry columns. Avoid inserting a full sheet row,
    # because that can trip protections on formula columns in the same row.
    leading_cols = COLUMNS[:17]
    leading_values = [[sheet_cell_value(row, col) for col in leading_cols]]
    execute_sheets_request(
        service.spreadsheets().values().update(
            spreadsheetId=spreadsheet_id,
            range=f"{worksheet_name}!A{row_number}:Q{row_number}",
            valueInputOption="USER_ENTERED",
            body={"values": leading_values},
        ),
        "append order",
    )
    skipped_columns = []
    trailing_cols = ["Paid?", "Last Updated", "Internal Notes"]
    for col in trailing_cols:
        col_idx = COLUMNS.index(col) + 1
        col_letter = get_column_letter(col_idx)
        try:
            execute_sheets_request(
                service.spreadsheets().values().update(
                    spreadsheetId=spreadsheet_id,
                    range=f"{worksheet_name}!{col_letter}{row_number}",
                    valueInputOption="USER_ENTERED",
                    body={"values": [[sheet_cell_value(row, col)]]},
                ),
                f"append order column {col}",
            )
        except Exception:
            skipped_columns.append(col)

    return skipped_columns


def load_orders() -> pd.DataFrame:
    if not gsheets_enabled():
        raise ValueError(
            "Google Sheets is not configured. Please set environment variables:\n"
            "- GOOGLE_SHEETS_SPREADSHEET_ID\n"
            "- GOOGLE_SERVICE_ACCOUNT_JSON\n"
            "- GOOGLE_SHEETS_WORKSHEET_NAME (optional, default: 'Orders')"
        )
    return load_orders_gsheets()


def save_orders(df: pd.DataFrame) -> list[str]:
    if not gsheets_enabled():
        raise ValueError(
            "Google Sheets is not configured. Please set environment variables:\n"
            "- GOOGLE_SHEETS_SPREADSHEET_ID\n"
            "- GOOGLE_SERVICE_ACCOUNT_JSON\n"
            "- GOOGLE_SHEETS_WORKSHEET_NAME (optional, default: 'Orders')"
        )
    return save_orders_gsheets(df)


def append_order(row: pd.Series) -> list[str]:
    if not gsheets_enabled():
        raise ValueError(
            "Google Sheets is not configured. Please set environment variables:\n"
            "- GOOGLE_SHEETS_SPREADSHEET_ID\n"
            "- GOOGLE_SERVICE_ACCOUNT_JSON\n"
            "- GOOGLE_SHEETS_WORKSHEET_NAME (optional, default: 'Orders')"
        )
    return append_order_gsheets(row)


def show_save_result(skipped_columns: list[str], target=st) -> None:
    if skipped_columns:
        target.warning(
            "Saved editable columns, but skipped protected columns: "
            + ", ".join(skipped_columns)
        )
    else:
        target.success("Saved ✅")


def show_google_write_error(e: Exception, target=st, action: str = "Save") -> None:
    message = str(e)
    if "protected cell" in message or "protected cell or object" in message:
        target.error(
            f"{action} failed because the Google Sheet is protected for this account. "
            "Unprotect the order entry columns/rows or give the service account edit permission for protected ranges."
        )
    else:
        target.error(f"{action} failed. Please check Google Sheets access and try again.")
    target.exception(e)


def save_orders_with_feedback(df: pd.DataFrame, target=st) -> bool:
    try:
        skipped_columns = save_orders(df)
        show_save_result(skipped_columns, target)
        return True
    except Exception as e:
        show_google_write_error(e, target, "Save")
        return False


def append_order_with_feedback(row: pd.Series, target=st) -> bool:
    try:
        skipped_columns = append_order(row)
        show_save_result(skipped_columns, target)
        return True
    except Exception as e:
        show_google_write_error(e, target, "Add order")
        return False


def generate_order_id(df: pd.DataFrame, prefix: str = "RO") -> str:
    date_part = datetime.now().strftime("%Y%m%d")
    pattern = re.compile(rf"^{re.escape(prefix)}-{date_part}-(\d+)$")
    max_sequence = 0

    if df is not None and "Order ID" in df.columns:
        for value in df["Order ID"].dropna():
            match = pattern.match(str(value).strip())
            if match:
                max_sequence = max(max_sequence, int(match.group(1)))

    return f"{prefix}-{date_part}-{max_sequence + 1:03d}"


def ensure_unique_order_id(order_id: str, df: pd.DataFrame, prefix: str = "RO") -> str:
    existing_ids = set()
    if df is not None and "Order ID" in df.columns:
        existing_ids = {
            str(value).strip()
            for value in df["Order ID"].dropna()
            if str(value).strip()
        }

    order_id = str(order_id or "").strip()
    if order_id and order_id not in existing_ids:
        return order_id

    next_id = generate_order_id(df, prefix)
    while next_id in existing_ids:
        head, sequence = next_id.rsplit("-", 1)
        next_id = f"{head}-{int(sequence) + 1:03d}"
    return next_id


def compute_profit_row(row: pd.Series) -> pd.Series:
    # Auto Total Price if missing: Labor + Part Price
    labor = row.get("Labor")
    part_cost = row.get("Part Cost")
    part_price = row.get("Part Price")
    total_price = row.get("Total Price")

    if pd.isna(total_price) or total_price == "" or total_price == 0:
        if pd.notna(labor) and pd.notna(part_price):
            row["Total Price"] = round(float(labor) + float(part_price), 2)
            total_price = row["Total Price"]

    if pd.notna(total_price) and pd.notna(part_cost):
        row["Profit"] = round(float(total_price) - float(part_cost), 2)

    # Round all price fields to 2 decimal places
    for price_col in ["Labor", "Part Cost", "Part Price", "Total Price", "Profit"]:
        if price_col in row and pd.notna(row.get(price_col)) and row.get(price_col) != "":
            try:
                row[price_col] = round(float(row[price_col]), 2)
            except (ValueError, TypeError):
                pass
    return row


def export_excel(df: pd.DataFrame) -> Path:
    ensure_dirs()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = EXPORT_DIR / f"orders_export_{ts}.xlsx"
    with pd.ExcelWriter(out, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Orders")
    return out


def generate_work_order_html(row: pd.Series) -> str:
    """Generate HTML for a customer-facing work order."""
    def safe_get(key, default=""):
        val = row.get(key, default)
        return str(val) if pd.notna(val) and val != "" else default
    
    order_id = safe_get("Order ID", "N/A")
    date = safe_get("Date", "")
    time = safe_get("Time", "")
    customer = safe_get("Customer", "")
    address = safe_get("Address", "")
    vehicle = safe_get("Vehicle (Year Make Model)", "")
    plate = safe_get("Plate", "")
    vin = safe_get("VIN", "")
    mileage = safe_get("Mileage", "")
    job_notes = safe_get("Job / Notes", "")
    paid = safe_get("Paid?", "")
    
    # Get price values - handle both numeric and string types
    labor_val = row.get("Labor", 0)
    part_price_val = row.get("Part Price", 0)
    total_price_val = row.get("Total Price", 0)
    
    # Convert to float if not already
    try:
        if pd.notna(labor_val) and labor_val != "":
            labor_val = float(labor_val)
        else:
            labor_val = 0.0
    except (ValueError, TypeError):
        labor_val = 0.0
    
    try:
        if pd.notna(part_price_val) and part_price_val != "":
            part_price_val = float(part_price_val)
        else:
            part_price_val = 0.0
    except (ValueError, TypeError):
        part_price_val = 0.0
    
    try:
        if pd.notna(total_price_val) and total_price_val != "":
            total_price_val = float(total_price_val)
        else:
            total_price_val = 0.0
    except (ValueError, TypeError):
        total_price_val = 0.0
    
    # Format prices
    labor_str = f"${labor_val:,.2f}"
    part_price_str = f"${part_price_val:,.2f}"
    total_price_str = f"${total_price_val:,.2f}"
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Work Order - {order_id}</title>
        <style>
            @media print {{
                @page {{
                    margin: 0.3in;
                }}
                body {{
                    margin: 0;
                    padding: 10px;
                }}
                .no-print {{
                    display: none;
                }}
            }}
            body {{
                font-family: Arial, sans-serif;
                max-width: 8.5in;
                margin: 0 auto;
                padding: 10px;
                color: #333;
                font-size: 11px;
            }}
            .header {{
                text-align: center;
                border-bottom: 2px solid #000;
                padding-bottom: 5px;
                margin-bottom: 8px;
            }}
            .shop-name {{
                font-size: 20px;
                font-weight: bold;
                margin-bottom: 2px;
            }}
            .work-order-title {{
                font-size: 14px;
                margin-top: 2px;
            }}
            .order-info {{
                display: grid;
                grid-template-columns: 1fr 1fr 1fr;
                gap: 8px;
                margin: 8px 0;
            }}
            .info-section {{
                background: #f5f5f5;
                padding: 6px;
                border-radius: 3px;
            }}
            .info-section h3 {{
                margin: 0 0 4px 0;
                border-bottom: 1px solid #333;
                padding-bottom: 2px;
                font-size: 11px;
            }}
            .info-row {{
                display: flex;
                justify-content: space-between;
                margin: 2px 0;
                font-size: 10px;
            }}
            .info-label {{
                font-weight: bold;
            }}
            .job-details {{
                margin: 6px 0;
                background: #f5f5f5;
                padding: 6px;
                border-radius: 3px;
            }}
            .job-details h3 {{
                margin: 0 0 4px 0;
                border-bottom: 1px solid #333;
                padding-bottom: 2px;
                font-size: 11px;
            }}
            .job-details p {{
                margin: 4px 0;
                font-size: 10px;
            }}
            .pricing {{
                margin: 6px 0;
                background: #f5f5f5;
                padding: 6px;
                border-radius: 3px;
            }}
            .pricing h3 {{
                margin: 0 0 4px 0;
                border-bottom: 1px solid #333;
                padding-bottom: 2px;
                font-size: 11px;
            }}
            .price-row {{
                display: flex;
                justify-content: space-between;
                margin: 3px 0;
                padding: 2px 0;
                font-size: 10px;
            }}
            .price-row.total {{
                border-top: 1px solid #333;
                border-bottom: 1px solid #333;
                font-size: 12px;
                font-weight: bold;
                padding: 4px 0;
                margin-top: 4px;
            }}
            .footer {{
                margin-top: 8px;
                padding-top: 6px;
                border-top: 1px solid #333;
                text-align: center;
                font-size: 9px;
            }}
            .footer p {{
                margin: 2px 0;
            }}
            .signature-section {{
                margin-top: 10px;
                display: grid;
                grid-template-columns: 1fr 1fr;
                gap: 20px;
            }}
            .signature-box {{
                border-top: 1px solid #333;
                padding-top: 3px;
                text-align: center;
                font-size: 10px;
            }}
            .print-button {{
                background: #4CAF50;
                color: white;
                padding: 10px 20px;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                font-size: 16px;
                margin: 20px 0;
            }}
            .print-button:hover {{
                background: #45a049;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="shop-name">Tianwin's Garage</div>
            <div class="work-order-title">WORK ORDER</div>
        </div>
        
        <div class="order-info">
            <div class="info-section">
                <h3>Order Information</h3>
                <div class="info-row">
                    <span class="info-label">Order ID:</span>
                    <span>{order_id}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Date:</span>
                    <span>{date}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Time:</span>
                    <span>{time}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Status:</span>
                    <span>{safe_get("Order Status", "")}</span>
                </div>
            </div>
            
            <div class="info-section">
                <h3>Customer Information</h3>
                <div class="info-row">
                    <span class="info-label">Customer:</span>
                    <span>{customer}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Address:</span>
                    <span>{address}</span>
                </div>
            </div>
            
            <div class="info-section">
                <h3>Vehicle Information</h3>
                <div class="info-row">
                    <span class="info-label">Vehicle:</span>
                    <span>{vehicle}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Plate:</span>
                    <span>{plate}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">VIN:</span>
                    <span>{vin}</span>
                </div>
                <div class="info-row">
                    <span class="info-label">Mileage:</span>
                    <span>{mileage}</span>
                </div>
            </div>
        </div>
        
        <div class="job-details">
            <h3>Job Description</h3>
            <p>{job_notes if job_notes else "N/A"}</p>
        </div>
        
        <div class="pricing">
            <h3>Pricing</h3>
            <div class="price-row">
                <span>Labor:</span>
                <span>{labor_str}</span>
            </div>
            <div class="price-row">
                <span>Parts:</span>
                <span>{part_price_str}</span>
            </div>
            <div class="price-row total">
                <span>Total:</span>
                <span>{total_price_str}</span>
            </div>
            <div class="price-row">
                <span>Paid:</span>
                <span>{paid if paid else "No"}</span>
            </div>
        </div>
        
        <div class="signature-section">
            <div class="signature-box">
                <div>Customer Signature</div>
            </div>
            <div class="signature-box">
                <div>Date</div>
            </div>
        </div>
        
        <div class="footer">
            <p>Thank you for choosing Tianwin's Garage!</p>
        </div>
    </body>
    </html>
    """
    return html


st.set_page_config(page_title="Auto Repair Orders", layout="wide")
st.markdown(
    """
    <style>
    .tw-stat-card {
        border-radius: 8px;
        padding: 16px;
        min-height: 218px;
    }
    .tw-stat-title {
        font-size: 15px;
        font-weight: 700;
        line-height: 1.25;
    }
    .tw-stat-subtitle,
    .tw-stat-label,
    .tw-stat-foot {
        font-size: 12px;
        line-height: 1.35;
        opacity: 0.72;
    }
    .tw-stat-subtitle {
        margin-top: 6px;
    }
    .tw-stat-days-left {
        font-size: 12px;
        font-weight: 650;
        line-height: 1.35;
        margin-top: 6px;
    }
    .tw-stat-primary {
        font-size: 34px;
        font-weight: 650;
        line-height: 1;
        margin-top: 14px;
    }
    .tw-stat-row {
        align-items: baseline;
        display: flex;
        gap: 8px;
        justify-content: space-between;
        margin-top: 12px;
        padding-top: 10px;
    }
    .tw-stat-row span {
        font-size: 12px;
        opacity: 0.72;
    }
    .tw-stat-row strong {
        font-size: 15px;
        font-weight: 650;
        text-align: right;
        white-space: nowrap;
    }
    .tw-stat-foot {
        margin-top: 10px;
    }
    .tw-stat-compare-label {
        font-size: 12px;
        font-weight: 650;
        margin-top: 14px;
        opacity: 0.82;
    }
    .tw-stat-compare {
        margin-top: 8px;
    }
    .tw-stat-compare-top,
    .tw-stat-bar-row {
        align-items: center;
        display: flex;
        gap: 8px;
        justify-content: space-between;
    }
    .tw-stat-compare-top span {
        font-size: 12px;
        opacity: 0.72;
    }
    .tw-stat-compare-top strong {
        font-size: 13px;
        font-weight: 650;
        white-space: nowrap;
    }
    .tw-stat-bar-row {
        margin-top: 4px;
    }
    .tw-stat-bar {
        border: 1px solid currentColor;
        border-radius: 999px;
        flex: 1;
        height: 8px;
        opacity: 0.7;
        overflow: hidden;
    }
    .tw-stat-bar-fill {
        background: currentColor;
        height: 100%;
    }
    .tw-stat-bar-pct {
        font-size: 11px;
        font-variant-numeric: tabular-nums;
        min-width: 34px;
        opacity: 0.72;
        text-align: right;
        white-space: nowrap;
    }
    .tw-payment-card {
        border-radius: 8px;
        padding: 14px 16px;
        min-height: 102px;
    }
    .tw-payment-title {
        font-size: 13px;
        font-weight: 700;
        line-height: 1.25;
    }
    .tw-payment-amount {
        font-size: 26px;
        font-weight: 700;
        line-height: 1;
        margin-top: 12px;
    }
    .tw-payment-foot {
        font-size: 12px;
        line-height: 1.35;
        margin-top: 10px;
        opacity: 0.72;
    }
    div[data-testid="stDataFrame"] {
        border-radius: 8px;
        overflow: hidden;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 6px;
        border-radius: 8px;
        padding: 4px;
    }
    .stTabs [data-baseweb="tab"] {
        border-radius: 6px;
        padding: 8px 12px;
    }
    div.stButton > button,
    div[data-testid="stFormSubmitButton"] button {
        border-radius: 8px;
    }
    </style>
    """,
    unsafe_allow_html=True,
)
st.title("🚗 Auto Repair Orders — Google Sheets")

if not gsheets_enabled():
    st.error(
        "❌ **Google Sheets is not configured.**\n\n"
        "Please set the following environment variables:\n"
        "- `GOOGLE_SHEETS_SPREADSHEET_ID`\n"
        "- `GOOGLE_SERVICE_ACCOUNT_JSON` (local path) or `GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT` / `[google_service_account]` in Streamlit secrets\n"
        "- `GOOGLE_SHEETS_WORKSHEET_NAME` (optional, default: 'Orders')\n\n"
        "Then restart the application."
    )
    st.stop()

sid, ws, sa = _sheets_env()
st.caption(f"Backend: **Google Sheets** | Tab: **{ws}**")

try:
    with st.spinner("Loading orders from Google Sheets..."):
        df = load_orders()
except Exception as e:
    st.error("❌ **Error loading orders from Google Sheets.**")
    st.info("This app uses Google Sheets as the only live source. Local CSV files are only for backups/demo exports.")
    st.exception(e)
    st.stop()

st.sidebar.header("Actions")

if st.sidebar.button("🔄 Reload from source"):
    st.cache_resource.clear()  # refresh service/auth cache if needed
    try:
        with st.spinner("Reloading orders from Google Sheets..."):
            st.session_state["df"] = load_orders()
        st.rerun()
    except Exception as e:
        st.sidebar.error("Reload failed. Google Sheets timed out again.")
        st.sidebar.exception(e)

if st.sidebar.button("💾 Save now"):
    save_orders_with_feedback(df, st.sidebar)

if st.sidebar.button("📦 Export Excel"):
    df2 = real_orders_df(df)
    out = export_excel(df2)
    st.sidebar.success(f"Exported: {out.name}")

if st.sidebar.button("⬇️ Export CSV"):
    ensure_dirs()
    df2 = real_orders_df(df)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = EXPORT_DIR / f"orders_export_{ts}.csv"
    df2.to_csv(out, index=False, encoding="utf-8-sig")
    st.sidebar.success(f"Exported: {out.name}")

st.sidebar.divider()
st.sidebar.subheader("📥 Import CSV")
uploaded_csv = st.sidebar.file_uploader("Upload CSV file", type=["csv"], accept_multiple_files=False)

if uploaded_csv is not None:
    try:
        new_df = pd.read_csv(uploaded_csv)
        missing = [c for c in COLUMNS if c not in new_df.columns]
        if missing:
            st.sidebar.error(f"Missing columns: {missing}")
        else:
            new_df = normalize_df(new_df)
            original_rows = len(new_df)
            new_df = real_orders_df(new_df)

            df_current = st.session_state.get("df", df).copy()
            merged = pd.concat([df_current, new_df], ignore_index=True)

            skipped_rows = original_rows - len(new_df)
            if skipped_rows:
                st.sidebar.info(f"Skipped {skipped_rows} blank rows.")
            if save_orders_with_feedback(merged, st.sidebar):
                st.session_state["df"] = merged
                df = merged
                st.sidebar.success(f"Imported {len(new_df)} rows successfully ✅")
    except Exception as e:
        st.sidebar.error(f"Import failed: {e}")

st.sidebar.divider()
st.sidebar.caption("Tip: use 'Reload from source' if you changed the sheet in Google.")


# Quick stats
st.subheader("📊 Quick Stats")
quick_df = dashboard_df(st.session_state.get("df", df))
stat_cols = st.columns(4)
for col, (title, subtitle, window_df, previous_df, previous_label, end_date) in zip(
    stat_cols,
    quick_stat_windows(quick_df),
):
    with col:
        render_quick_stat_card(title, subtitle, window_df, previous_df, previous_label, end_date)

payment_summary = payment_income_summary(quick_df)
cash_total = payment_summary["Cash"]["total"]
zelle_total = payment_summary["Zelle"]["total"]
cash_orders = payment_summary["Cash"]["orders"]
zelle_orders = payment_summary["Zelle"]["orders"]

st.markdown("#### Payment Income")
payment_cols = st.columns(3)
with payment_cols[0]:
    render_payment_income_card("Cash Income", cash_orders, cash_total)
with payment_cols[1]:
    render_payment_income_card("Zelle Income", zelle_orders, zelle_total)
with payment_cols[2]:
    render_payment_income_card("Cash + Zelle", cash_orders + zelle_orders, cash_total + zelle_total)

st.divider()

tabs = st.tabs(["🧾 Orders Table", "📋 All Details", "➕ Add Order", "📈 Stats", "🖨️ Print Work Order"])

with tabs[0]:
    st.subheader("Orders Table")
    st.caption("Past 30 days, plus future appointments and active work.")
    recent_df = order_overview_df(df, days=30)
    summary_cols = [col for col in ORDER_SUMMARY_COLUMNS if col in recent_df.columns]
    recent_summary = recent_df[summary_cols].copy()
    recent_height = table_height(len(recent_df))

    if recent_df.empty:
        st.info("No dated orders found in the past 30 days.")
    else:
        st.dataframe(
            style_order_table(recent_summary),
            use_container_width=True,
            hide_index=True,
            height=recent_height,
        )

with tabs[1]:
    st.subheader("All Detail Orders")
    st.caption("Full editable sheet. Save writes back to Google Sheets.")
    detail_height = table_height(len(df))

    edited = st.data_editor(
        df,
        use_container_width=True,
        num_rows="dynamic",
        height=detail_height,
        column_config={
            "Order Status": st.column_config.SelectboxColumn("Order Status", options=ORDER_STATUS_OPTIONS),
            "Part Status": st.column_config.SelectboxColumn("Part Status", options=PART_STATUS_OPTIONS),
            "Paid?": st.column_config.SelectboxColumn("Paid?", options=PAID_OPTIONS),
            "Labor": st.column_config.NumberColumn("Labor", format="$%.2f"),
            "Part Cost": st.column_config.NumberColumn("Part Cost", format="$%.2f"),
            "Part Price": st.column_config.NumberColumn("Part Price", format="$%.2f"),
            "Total Price": st.column_config.NumberColumn("Total Price", format="$%.2f"),
            "Profit": st.column_config.NumberColumn("Profit", format="$%.2f"),
        },
    )

    if st.button("Save changes"):
        if save_orders_with_feedback(edited, st):
            st.session_state["df"] = load_orders()
            st.rerun()

with tabs[2]:
    st.subheader("Add Order (form)")
    base = {c: "" for c in COLUMNS}
    current_orders_df = st.session_state.get("df", df)
    suggested_order_id = generate_order_id(current_orders_df)

    with st.form("order_form", clear_on_submit=True):
        a, b, c = st.columns(3)
        base["Order Status"] = a.selectbox("Order Status", ORDER_STATUS_OPTIONS, index=1)
        base["Order ID"] = b.text_input("Order ID", value=suggested_order_id)
        base["Date"] = c.text_input("Date (e.g., 1.16.2026 or 2026-01-16)")

        d, e, f = st.columns(3)
        base["Time"] = d.text_input("Time (e.g., 10:00 AM)")
        base["Address"] = e.text_input("Address / City")
        base["Customer"] = f.text_input("Customer")

        g, h, i = st.columns(3)
        base["Vehicle (Year Make Model)"] = g.text_input("Vehicle (Year Make Model)")
        base["Plate"] = h.text_input("Plate")
        base["VIN"] = i.text_input("VIN")

        j, k = st.columns(2)
        base["Mileage"] = j.number_input("Mileage", min_value=0, value=0, step=100)
        base["Labor"] = k.number_input("Labor ($)", min_value=0.0, value=0.0, step=0.01, format="%.2f")

        base["Paid?"] = st.selectbox("Paid?", PAID_OPTIONS, index=1)
        base["Job / Notes"] = st.text_area("Job / Notes")

        st.markdown("### Part")
        p1, p2, p3 = st.columns(3)
        base["Part Name"] = p1.text_input("Part Name")
        base["Part Status"] = p2.selectbox("Part Status", PART_STATUS_OPTIONS, index=0)
        base["Part Notes"] = p3.text_input("Part Notes (return / fitment / etc.)")

        p4, p5, p6 = st.columns(3)
        base["Part Cost"] = p4.number_input("Part Cost ($)", min_value=0.0, value=0.0, step=0.01, format="%.2f")
        base["Part Price"] = p5.number_input("Part Price ($) (charged)", min_value=0.0, value=0.0, step=0.01, format="%.2f")
        base["Total Price"] = p6.number_input("Total Price ($) (charged)", min_value=0.0, value=0.0, step=0.01, format="%.2f")

        base["Internal Notes"] = st.text_area("Internal Notes")
        submitted = st.form_submit_button("Add order")

    if submitted:
        row = pd.Series(base)
        row["Order ID"] = ensure_unique_order_id(row.get("Order ID", ""), current_orders_df)
        row["Last Updated"] = now_str()

        if append_order_with_feedback(row, st):
            st.session_state["df"] = load_orders()
            st.success("Order added ✅")
            st.rerun()

with tabs[3]:
    st.subheader("Business Dashboard")
    raw_dashboard_df = st.session_state.get("df", df)
    dfx = dashboard_df(raw_dashboard_df)
    blank_rows = len(raw_dashboard_df) - len(dfx)

    if dfx.empty:
        st.info("No real orders found yet.")
    else:
        min_date = dfx["Date Parsed"].min()
        max_date = dfx["Date Parsed"].max()
        date_label = "No valid dates"
        if pd.notna(min_date) and pd.notna(max_date):
            date_label = f"{min_date:%b %d, %Y} to {max_date:%b %d, %Y}"

        st.caption(f"Analyzing {len(dfx)} real orders. Date range: {date_label}. Ignored {blank_rows} blank sheet rows.")

        total_revenue = dfx["Total Price"].sum()
        total_profit = dfx["Profit"].sum()
        total_part_cost = dfx["Part Cost"].sum()
        avg_ticket = total_revenue / len(dfx) if len(dfx) else 0
        margin_pct = (total_profit / total_revenue * 100) if total_revenue else 0
        unpaid_value = dfx.loc[dfx["Paid Status"].ne("Yes"), "Total Price"].sum()
        completed_orders = int(dfx["Order Status"].eq("Completed").sum())

        k1, k2, k3, k4, k5, k6 = st.columns(6)
        k1.metric("Orders", len(dfx))
        k2.metric("Completed", completed_orders)
        k3.metric("Revenue", money(total_revenue))
        k4.metric("Profit", money(total_profit))
        k5.metric("Margin", f"{margin_pct:.1f}%")
        k6.metric("Unpaid / Unknown", money(unpaid_value))

        st.divider()

        trend_tab, customer_tab, operations_tab, quality_tab = st.tabs(
            ["Financial Trends", "Customers", "Operations", "Data Quality"]
        )

        with trend_tab:
            st.markdown("### Weekly Financial Trends")
            valid_dates = dfx[dfx["Date Parsed"].notna()].copy()
            if valid_dates.empty:
                st.info("No valid dates available for trend charts.")
            else:
                weekly = (
                    valid_dates.groupby("Week")[["Total Price", "Profit", "Part Cost"]]
                    .sum()
                    .sort_index()
                    .round(2)
                    .reindex(
                        pd.date_range(
                            valid_dates["Week"].min(),
                            valid_dates["Week"].max(),
                            freq="W-MON",
                        ),
                        fill_value=0,
                    )
                    .reset_index()
                    .rename(columns={"index": "Week"})
                    .rename(columns={"Total Price": "Revenue", "Part Cost": "Parts Cost"})
                )
                weekly_long = weekly.melt(
                    id_vars="Week",
                    value_vars=["Revenue", "Profit", "Parts Cost"],
                    var_name="Metric",
                    value_name="Amount",
                )
                weekly_chart = (
                    alt.Chart(weekly_long)
                    .mark_line(point=True)
                    .encode(
                        x=alt.X("Week:T", title="Week"),
                        y=alt.Y("Amount:Q", title="Amount ($)"),
                        color=alt.Color("Metric:N", title="Metric"),
                        tooltip=[
                            alt.Tooltip("Week:T", title="Week", format="%Y-%m-%d"),
                            alt.Tooltip("Metric:N", title="Metric"),
                            alt.Tooltip("Amount:Q", title="Amount", format="$,.2f"),
                        ],
                    )
                    .properties(height=360)
                )
                st.altair_chart(weekly_chart, use_container_width=True)

                c_left, c_right = st.columns(2)
                with c_left:
                    monthly = (
                        valid_dates.groupby("Month")[["Total Price", "Profit"]]
                        .sum()
                        .sort_index()
                        .round(2)
                    )
                    monthly.index = monthly.index.strftime("%Y-%m")
                    st.markdown("### Monthly Summary")
                    st.dataframe(
                        monthly.rename(columns={"Total Price": "Revenue"}),
                        use_container_width=True,
                    )
                with c_right:
                    st.markdown("### Ticket Size")
                    st.metric("Average Ticket", money(avg_ticket))
                    st.metric("Average Profit / Order", money(total_profit / len(dfx)))
                    st.metric("Parts Cost", money(total_part_cost))

        with customer_tab:
            customer_summary = (
                dfx.groupby("Customer Display")
                .agg(
                    Orders=("Customer Display", "size"),
                    Revenue=("Total Price", "sum"),
                    Profit=("Profit", "sum"),
                    Last_Order=("Date Parsed", "max"),
                )
                .sort_values("Revenue", ascending=False)
                .head(15)
                .reset_index()
                .rename(columns={"Customer Display": "Customer"})
            )
            customer_summary["Revenue"] = customer_summary["Revenue"].round(2)
            customer_summary["Profit"] = customer_summary["Profit"].round(2)
            customer_summary["Last_Order"] = customer_summary["Last_Order"].dt.strftime("%Y-%m-%d").fillna("")

            left, right = st.columns([2, 1])
            with left:
                st.markdown("### Top Customers")
                st.dataframe(customer_summary, use_container_width=True, hide_index=True)
            with right:
                top_customer = customer_summary.iloc[0] if not customer_summary.empty else None
                if top_customer is not None:
                    st.metric("Top Customer", top_customer["Customer"])
                    st.metric("Top Customer Revenue", money(top_customer["Revenue"]))
                repeat_customers = int((dfx["Customer Display"].value_counts() > 1).sum())
                st.metric("Repeat Customers", repeat_customers)

        with operations_tab:
            left, right = st.columns(2)
            with left:
                st.markdown("### Orders by Status")
                status_counts = dfx["Order Status"].fillna("").replace("", "Missing").value_counts()
                st.bar_chart(status_counts)

                st.markdown("### Service Mix")
                service_counts = dfx["Service Category"].value_counts()
                st.bar_chart(service_counts)

            with right:
                st.markdown("### Parts by Status")
                part_counts = dfx["Part Status"].fillna("").replace("", "No parts listed").value_counts()
                st.bar_chart(part_counts)

                st.markdown("### Payment Status")
                payment_summary = (
                    dfx.groupby("Paid Status")[["Total Price", "Profit"]]
                    .sum()
                    .sort_values("Total Price", ascending=False)
                    .round(2)
                )
                st.dataframe(
                    payment_summary.rename(columns={"Total Price": "Revenue"}),
                    use_container_width=True,
                )

            st.markdown("### Open / Unpaid Work")
            open_work = dfx[
                dfx["Order Status"].ne("Completed") | dfx["Paid Status"].ne("Yes")
            ].copy()
            open_cols = [
                "Date",
                "Customer",
                "Vehicle (Year Make Model)",
                "Order Status",
                "Part Status",
                "Paid?",
                "Total Price",
                "Profit",
                "Job / Notes",
            ]
            open_work = open_work.sort_values("Date Parsed", na_position="last")
            st.dataframe(open_work[open_cols], use_container_width=True, hide_index=True)

        with quality_tab:
            st.markdown("### Data Quality Checks")
            missing_date = int(dfx["Date Parsed"].isna().sum())
            missing_customer = int(dfx["Customer"].fillna("").astype(str).str.strip().eq("").sum())
            missing_vehicle = int(dfx["Vehicle (Year Make Model)"].fillna("").astype(str).str.strip().eq("").sum())
            missing_payment = int(dfx["Paid Status"].eq("Unknown").sum())

            q1, q2, q3, q4 = st.columns(4)
            q1.metric("Invalid Dates", missing_date)
            q2.metric("Missing Customer", missing_customer)
            q3.metric("Missing Vehicle", missing_vehicle)
            q4.metric("Unknown Payment", missing_payment)

            issue_mask = (
                dfx["Date Parsed"].isna()
                | dfx["Customer"].fillna("").astype(str).str.strip().eq("")
                | dfx["Vehicle (Year Make Model)"].fillna("").astype(str).str.strip().eq("")
                | dfx["Paid Status"].eq("Unknown")
            )
            issue_cols = [
                "Date",
                "Customer",
                "Vehicle (Year Make Model)",
                "Order Status",
                "Paid?",
                "Total Price",
                "Job / Notes",
            ]
            st.dataframe(dfx.loc[issue_mask, issue_cols], use_container_width=True, hide_index=True)

with tabs[4]:
    st.subheader("🖨️ Print Work Order")
    st.caption("Select an order to generate a customer-facing work order for printing.")
    
    if len(df) == 0:
        st.info("No orders available. Please add an order first.")
    else:
        # Create a selection interface
        df_display = df.copy()
        # Create a display string for each order
        df_display["Select"] = df_display.apply(
            lambda row: f"Order ID: {row.get('Order ID', 'N/A')} | Customer: {row.get('Customer', 'N/A')} | Date: {row.get('Date', 'N/A')}",
            axis=1
        )
        
        selected_index = st.selectbox(
            "Select an order to print:",
            options=range(len(df)),
            format_func=lambda x: df_display.iloc[x]["Select"]
        )
        
        if selected_index is not None:
            selected_order = df.iloc[selected_index]
            
            # Show preview
            st.markdown("### Order Preview")
            preview_cols = st.columns(3)
            with preview_cols[0]:
                st.write(f"**Order ID:** {selected_order.get('Order ID', 'N/A')}")
                st.write(f"**Customer:** {selected_order.get('Customer', 'N/A')}")
            with preview_cols[1]:
                st.write(f"**Date:** {selected_order.get('Date', 'N/A')}")
                st.write(f"**Vehicle:** {selected_order.get('Vehicle (Year Make Model)', 'N/A')}")
            with preview_cols[2]:
                total = selected_order.get('Total Price', 0)
                try:
                    total_str = f"${float(total):,.2f}"
                except (ValueError, TypeError):
                    total_str = f"${total}"
                st.write(f"**Total:** {total_str}")
            
            # Generate HTML
            work_order_html = generate_work_order_html(selected_order)
            
            # Display the HTML
            st.markdown("---")
            st.markdown("### Work Order (Click Print button or use browser's Print function)")
            st.components.v1.html(work_order_html, height=800, scrolling=True)
            
            # Download button for HTML file
            order_id = selected_order.get('Order ID', 'N/A')
            safe_order_id = "".join(c for c in str(order_id) if c.isalnum() or c in ('-', '_')).strip() or "order"
            filename = f"work_order_{safe_order_id}_{datetime.now().strftime('%Y%m%d')}.html"
            
            st.download_button(
                label="📥 Download Work Order (HTML)",
                data=work_order_html,
                file_name=filename,
                mime="text/html"
            )
